---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 17, 18]

    steps:
      - name: Prepare
        id: prep
        run: |
          if [[ ${GITHUB_REF##*/} == "main" ]]; then
            echo push=true >> $GITHUB_OUTPUT
          else
            echo push=false >> $GITHUB_OUTPUT
          fi
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          build-args: VERSION=${{ matrix.version }}
          push: ${{ steps.prep.outputs.push }}
          tags: ${{ secrets.DOCKER_HUB_USER }}/clang-format:${{ matrix.version }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
